name: C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Dependencies
      run: sudo apt-get install -y build-essential libgtest-dev

    - name: Build
      run: make
    
    - name: Chmod
      run: chmod +x ./tests
    
    - name: Ls
      run: ls
      
    - name: Test
      run: ./tests
